name: VimdowManager
options:
  minimumXcodeGenVersion: "2.46.0"
  projectFormat: xcode15_0
  defaultConfig: Release
  developmentLanguage: en
  useBaseInternationalization: false
  deploymentTarget:
    macOS: "14.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: "6.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
    Release:
      ONLY_ACTIVE_ARCH: NO
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    exactVersion: 3.1.0
targets:
  VimdowCore:
    type: library.static
    platform: macOS
    sources: [Sources/VimdowCore]
    settings:
      base:
        DEFINES_MODULE: YES
        SKIP_INSTALL: YES
  VimdowManager:
    type: application
    platform: macOS
    sources:
      - path: VimdowManager
      - path: launcher.icns
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: VimdowManager/VimdowManager-Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: rath.toys.VimdowManager
        PROVISIONING_PROFILE_SPECIFIER: ""
    dependencies:
      - target: VimdowCore
      - package: KeyboardShortcuts
  VimdowCoreTests:
    type: bundle.unit-test
    platform: macOS
    sources: [Tests/VimdowCoreTests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: rath.toys.VimdowCoreTests
    dependencies:
      - target: VimdowCore
  VimdowShortcutTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/VimdowShortcutTests
      - VimdowManager/ShortcutController.swift
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: rath.toys.VimdowShortcutTests
    dependencies:
      - target: VimdowCore
      - package: KeyboardShortcuts
schemes:
  VimdowManager:
    build:
      targets:
        VimdowManager: all
    run:
      config: Debug
    test:
      targets: [VimdowCoreTests]
      gatherCoverageData: true
    profile:
      config: Release
    archive:
      config: Release
  VimdowCore:
    build:
      targets:
        VimdowCore: all
    test:
      targets: [VimdowCoreTests]
      gatherCoverageData: true
  VimdowShortcuts:
    build:
      targets:
        VimdowCore: all
    test:
      targets: [VimdowShortcutTests]
      parallelizable: false
